name: Portfolio Update

on:
  push:
    branches: "main"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Override CI environment variable
        run: echo 'CI=false' >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci
        # run: npm ci

      - name: Test
        run: cat package.json

      - uses: actions/checkout@v4
      - name: Git user configuration
        run: |
          git remote set-url origin https://x-access-token:${PORTFOLIO_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: deploy
        run: npm run deploy