name: 'deploy-frontend'

on:
  push:
    branches:
    - main

jobs:
  deployment:
    name: 'deploy-frontend'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run: 
        shell: bash
        working-directory: ./
    env:
      CI: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: See content
        run: ls -la

      - name: Upload to S3
        run: aws s3 sync build/ s3://portfolio-website-viniciusg23/ --delete
          
      
  check-run:
    needs: deployment
    runs-on: ubuntu-latest
    steps:
    - name: check
      run: |-
        if [[ ${{ needs.deployment.result }} == 'success' ]]; then
          exit 0;
        else:
          exit 1;
        fi