name: Deploy Github Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          
      - name: Configure git
        run: |
          git config --global user.email "support+actions@github.com"
          git config --global user.name "github-actions-bot"
  
      - name: Install dependencies
        run: npm install
      # - name: Build NPM package
      #   run: npm run build:lib

      - name: Publish github pages
        run: |
          echo ${GITHUB_REPOSITORY}
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -u "github-actions-bot <support+actions@github.com>"
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
