name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Set up environment
      run: |
        echo "CI=false" >> $GITHUB_ENV
        git config --global user.email "viniciusgonzagaguilherme@gmail.com"
        git config --global user.name "viniciusg23"
    - name: Install dependencies
      run: npm install
    - name: Deploy to GitHub Pages
      run: npm run deploy
